language: node_js
node_js:
- 10.15.3

after_success: 
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls

cache:
  directories:
  - node_modules

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE automart_test;" -U postgres
  - psql -c "CREATE USER orley WITH PASSWORD 'password';" -U postgres